/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://qy4swslhfvhqhj2bjpivm2itwu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fk2x7u7g4jaalgzvyucfqakckq",
    "aws_cognito_identity_pool_id": "eu-west-1:673c9dec-659b-4c40-8615-d3a0c6ade914",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rGgRSIxB3",
    "aws_user_pools_web_client_id": "1f3qanlfvcjqa8juaeriad1sjs",
    "oauth": {}
};


export default awsmobile;
